### ISSUE TITLE
Remove per-element tag queries

### ISSUE THREAD

**Issue by pnorman** [zerebubuth/openstreetmap-cgimap#123]
#122 does raise a valid issue, even if buried and unclear.

Currently each object in the output requires a SQL query to fetch its tags. I had looked at this in GSoC and noted it as a performance problem, but lower priority than other work.

In the examples below I'm just using nodes, but they'd apply to other object types too.

My thought at the time was to have tags returned at the time of selection, in a query that returns the tags as a column, either of type hstore, an array of alternating values, or two arrays. I'm inclined towards two arrays because I believe that to be easiest.

This would be something like
```sql
select n.id, ..., array_agg(k) keys, array_agg(v) vals
  FROM current_nodes n
    JOIN current_node_tags t ON (n.id=t.node_id)
  WHERE ...
  GROUP BY n.id -- primary key, so should work instead of listing all node columns
```

**Comment by pnorman** [comment]
Fixed for nodes in #130, but other object types remain

**Comment by jronak** [comment]
@pnorman #130 fixed for all the types, the title was incorrect. Please verify

**Comment by zerebubuth** [comment]
Yup, #130 fixes it for all object types - including changesets.

I think the next steps are to do similar things for the way nodes and relation members, then extend that to the `readonly_apidb_backend`. And, after I merge #129, extend to the history calls as well (because they have a composite primary key on `id, version` they need similar, but slightly different, queries).

At some point I also want to see whether `writeable_apidb_backend` and `readonly_apidb_backend` can be refactored to share more code. At the moment, they share very little, but I feel like they ought to be able to share a great deal more since the table schema is identical.

**Comment by jronak** [comment]
@zerebubuth I think this issue can be closed now

**Comment by zerebubuth** [comment]
Yup, good point.
