### ISSUE TITLE
oauth: boost::spirit::qi::expectation_failure

### ISSUE THREAD

**Issue by mmd-osm** [zerebubuth/openstreetmap-cgimap#146]
I was testing some use cases according to the osm website changeset_controller_test.rb file, and noticed an issue with OAuth header parsing. Somehow all test cases use an apostrophe for XML attributes (like in `<node id='#{node.id}'`), and parts of this gets included in the OAuth Auth header. 

Unfortunately, using `'` instead of `"` triggers an HTTP 500 Internal Server error along with an Exception: boost::spirit::qi::expectation_failure. I'm suspecting that this case isn't covered in the parser implementation in oauth.cpp.

 (mod_fastcgi.c.3021) backend died; we'll disable it for 1 seconds and send the request to another backend instead: reconnects: 0 load: 1 

curl statement to reproduce from command line:

```
curl -v 'http://localhost:31337/api/0.6/changeset/876/download' -H 'Accept: */*'  -H 'Content-Type: application/x-www-form-urlencoded' -H $'Authorization: OAuth %3Cdummy%20id="\'-1\'%2F%3E", oauth_consumer_key="U84xxVrHBewaYHehTpaV0Rk3nGhahzRj0zntCe1N", oauth_nonce="Xw1WlI", oauth_signature="32gRmihzmdV47jW2juAL7mIpXkA%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1526814151", oauth_token="FLfg7mbQlV6TAcBSY58YgQz39mpcWgj47J3PZPEx"'
```

BTW: the request was generated by https://github.com/osmlab/osm-auth, maybe there's some issue in that library as well. It shouldn't trigger a crash on cgimap side though.

**Comment by zerebubuth** [comment]
Yup, you're right. That should be a parse fail rather than a crash.

Digging into the cause of the failure, it seems to be that `%3Cdummy%20id="'-1'%2F%3E"` is causing it because `'` (single quote) is not escaped, but is not in the [unreserved set of characters](https://tools.ietf.org/html/rfc3986#section-2.3) that are [mandated by the OAuth spec](https://oauth.net/core/1.0a/#rfc.section.5.1). This would appear to be an issue with whatever generated that OAuth header - although it could have been unquoted by a browser or other tool trying to be helpful. How did you generate that string?

The string looks a bit weird to me: `%3Cdummy%20id="'-1'%2F%3E"` unquotes to `<dummy id="'-1'/>"`, which looks an awful lot like:

```python
s = "<dummy id='-1'/>"
k, v = s.split('=')
print "%s=\"%s\"" % (k, v)
# writes: <dummy id="'-1'/>"
```

I don't understand why there'd be some random XML in the OAuth header. But regardless - the parse fail should be only a fail, not a crash.

**Comment by mmd-osm** [comment]
Adding `options: { header: { 'Content-Type': 'text/xml' } },` in my script seems to do the trick, the strange header is gone now. Good that's we've also fixed the parsing issue in cgimap along the way.
