### ISSUE TITLE
history api returns wrong tag data for ways

### ISSUE THREAD

**Issue by GerdP** [zerebubuth/openstreetmap-cgimap#181]
The api call
​https://www.openstreetmap.org/api/0.6/way/158601617/history
returns a lot of duplicated tags for each version, it seems that a join is done without using the version number. Attached is the result.
[history.txt](https://github.com/zerebubuth/openstreetmap-cgimap/files/3220070/history.txt)

**Comment by tomhughes** [comment]
This appears to be specified to running in readonly mode.

**Comment by mmd-osm** [comment]
@GerdP : your assumption is correct, there's a version number missing in the following JOIN condition to extract historic ways:

https://github.com/zerebubuth/openstreetmap-cgimap/blob/master/src/backend/apidb/writeable_pgsql_selection.cpp#L697

**Comment by GerdP** [comment]
I've never looked at the sources for cgimap before but I was quite surprised to see that the sqls in writeable_pgsql_selection.cpp and readonly_pgsql_selection.cpp are so very different. I wonder why no test found this quite obvious problem?

**Comment by mmd-osm** [comment]
It looks like the code in question about 2-3 years old, and tags weren't covered in the unit test before. They have been added now. I also double checked that the previous, incorrect query made the test fail.

As to why both backends are so different, I don't know exactly. It's probably because in one case, you can leverage temporary tables to store intermediate results, whereas for the read-only backend you need to transfer data back and forth between cgimap and the database.

**Comment by tomhughes** [comment]
The history is that it was originally written using temporary tables and then there came a time when we need to be able to run against a readonly replica when you can't do that so the readonly backend was written. At that point I think only the map call was implemented.

Since then other calls have been implemented but we were unintentionally running in readonly mode when we didn't need to so we didn't notice.

By the way, it's wrong for cgimap to refuse to upload when in readonly mode (as it currently does) because the upload host might be writable - our backup data centre currently uses different databases for read and write and hence runs in readonly mode so that read calls can be sent to a replica.

**Comment by mmd-osm** [comment]
> By the way, it's wrong for cgimap to refuse to upload when in readonly mode (as it currently does) because the upload host might be writable

Yes, that makes sense. I tried to address this issue in: https://github.com/zerebubuth/openstreetmap-cgimap/pull/185 by introducing a new --disable-api-write command line parameter, which could be set in case of db maintenance.
