### ISSUE TITLE
Reject unknown API calls

### ISSUE THREAD

**Issue by pnorman** [zerebubuth/openstreetmap-cgimap#52]
A request to `/api/0.6/way/#id/foo` functions the same as a request to `/api/0.6/way/#id`.

This caused me some confusion when trying to figure out why I wasn't getting back ways and nodes (I was on a branch without full handlers moved out of experimental).

Not a huge issue because the HTTP server config directing to cgimap probably won't normally direct requests it can't handle, but a clearer error would be nice.

**Comment by zerebubuth** [comment]
I've added a failing unit test for this in [branch `52-unknown-api-calls`](https://github.com/zerebubuth/openstreetmap-cgimap/tree/52-unknown-api-calls). The test output is:

```
FAIL: test/routes
=================

EXCEPTION: Header key `Status'; expected `404 Not Found' but got `200 OK'., 
  in "./test/routes.testcore/way_id_extra.case" test.
FAIL test/routes.testcore (exit status: 1)
```

The reason for this is that `./test/routes.testcore/way_id_extra.case` attempts to fetch `/api/0.6/way/1/foo`, which doesn't exist as an API call. The way the matching works is that it's not anchored to the end of the string, so [`routes.cpp`](https://github.com/zerebubuth/openstreetmap-cgimap/blob/0a4b0c6a59d259aafe4801b9d0c1dae4c57a6da6/src/routes.cpp#L150-L152) tries first to match against `/api/0.6/way/#{id}/full` and that doesn't match, so then it tries `/api/0.6/way/#{id}` and that _does_ match, with some garbage (`/foo`) on the end which it ignores.

To fix this bug, we need to update the route matching so that the match must be against the full path, and trailing garbage is not allowed.

Alternatively, one could rewrite the whole route matching code. It's fairly gnarly and horrible at the moment, and could be a lot nicer if it took advantage of C++11 features such as variadic templates. The original aim of the code was to have a nice set of "Rails-like" routes rather than a big if-else-if block or a blob of regular expressions, but I'm happy to throw away the code for a better implementation if it gets closer to that aim.

**Comment by jronak** [comment]
Thanks for such a brief explanation, I totally forgot about testing such request path. I read through the routes code after this and I have a rough idea of how it works. I shall understand it properly and get back to you.
